### PR TITLE
Shorten duration description and fix some minor English errors

### PR DESCRIPTION
**Pull request by LiamBull**
I hope this isn't too much of a nit pick. The old description had a few spelling errors, and I felt it was quite wordy. I think the simplified description is much clearer.

### CODE REVIEW

**Review by a-toms — APPROVED** [review]
Much clearer.

**Comment by LiamBull** [comment]
@a-toms Is this going to be merged? I see that this repo still gets commit to, but many of the PRs to the docs are very stale.

If this isn't going to be merged I'd rather close it to remove clutter on my end.

**Comment by arshaw** [comment]
Earlier this year I renamed the `master` branch to `main` and this had the side effect of accidentally closing many PRs, including this one. I thought Github would have handled this more gracefully. Very sorry about that!

I've given a label to this PR to keep track. I will triage these PRs as if they were "Open".

**Comment by arshaw** [comment]
Merged this and refined a little bit more. Thanks!

https://fullcalendar.io/docs/v5/upgrading-from-v4#event-data

**Pull request merged**
