### PR TITLE
Updated React Component Markdown to utilize React's functional components and hooks.

### PR DESCRIPTION
**Pull request by mohammednumaan**
This updated markdown includes code snippets that utilize React's functional components and hooks.

### CODE REVIEW

**Comment by mohammednumaan** [comment]
@arshaw @acerix Hey there! I was wondering if you could lend a hand by taking a quick look at the issue? Your help would be greatly appreciated!

**Comment by arshaw** [comment]
Thank you very much for this @mohammednumaan . I merged it and ended up completely converting over to function components. All devs seem to be comfortable with them these days:

https://fullcalendar.io/docs/react

Thanks!

**Comment by mohammednumaan** [comment]
@arshaw I noticed a red highlight in one of the code snippets. Could this be a lint issue? (i have attached it below)
And no problem! I'll be happy to contribute more to this repo in the future. 😄 

issue

**Comment by arshaw** [comment]
It's just a problem with the syntax highlighter my website uses. It trips up a bit on JSX. I'll eventually upgrade it! Thanks again!

**Pull request merged**
